name: graph_paper
version: 0.1.0
author: Adam J. Cook <adam.joseph.cook@gmail.com>
description: Web component for generating various types of engineering graph paper using SVG, written in Dart and Polymer.
homepage: https://github.com/adamjcook/graph-paper
dependencies:
  polymer: '>=0.14.0+1 <0.15.0'
  quiver: '>=0.18.2 <0.19.0'
  web_components: '>=0.7.0 <0.8.0'
dev_dependencies:
  core_elements: '>=0.2.1+1 <0.3.0'
  html5lib: '>=0.12.0 <0.13.0'
  paper_elements: '>=0.2.0 <0.3.0'
  path: '>=1.3.0 <2.0.0'
  unittest: '>=0.11.0+5 <0.12.0'
  yaml: '>=2.0.1+1 <3.0.0'
environment:
  sdk: '>=1.6.0'
transformers:
- polymer:
    entry_points:
    - web/index.html
    lint: false