name: statechart
version: 0.1.0
author: Adam J. Cook <adam.joseph.cook@gmail.com>
description: Library for constructing and working with Harel statecharts, written in Dart.
homepage: https://github.com/adamjcook/statechart.dart
documentation: https://github.com/adamjcook/statechart.dart
environment:
  sdk: '>=1.5.0'
dependencies:
  logging: '>=0.9.1+1 <0.10.0'
dev_dependencies:
  unittest: '>=0.11.0+3 <0.12.0'